Added Turkish translations
thomasgriffin/TGM-Plugin-Activation pull request #679
Opened 2017-07-29 02:32 UTC by karalamalar

2017-07-29 07:05 UTC, GaryJones requested changes

2017-07-29 07:05 UTC, GaryJones commented on languages/tgmpa-tr_TR.po
> +"Project-Id-Version: TGM Plugin Activation\n"
Can you add in a version as well, please?

2017-07-29 07:17 UTC, karalamalar commented on languages/tgmpa-tr_TR.po
> +"Project-Id-Version: TGM Plugin Activation\n"
Done

2017-07-29 15:42 UTC, GaryJones approved these changes

2017-08-03 08:51 UTC, jrfnl commented
Hi @karalamalar Thank you for this translation! We love it when people make TGMPA available in new language.
The PR unfortunately will need to be rebased (and squashed) before I can merge it. Would you like to do this yourself or shall I do it for you ?

2017-08-03 09:08 UTC, karalamalar commented
Done. Your turn. 😄

2017-08-03 09:10 UTC, merged

2017-08-03 09:13 UTC, jrfnl commented
Thank you so much! And... my part is done too ;-) (including the - as of yet local - changelog entry with your credits :heart_eyes_cat:  )