Add Japanese translation file.
thomasgriffin/TGM-Plugin-Activation pull request #683
Opened 2017-08-09 02:16 UTC by mayukojpn

2017-08-09 11:41 UTC, GaryJones requested changes
Couple of header strings to change please, then good to go.

2017-08-09 11:41 UTC, GaryJones commented on languages/tgmpa-ja.po
> +"Last-Translator: Juliette Reinders Folmer <wpplugins_nospam@adviesenzo.nl>\n"
Please update this to your details @mayukojpn :-)

2017-08-09 11:41 UTC, GaryJones commented on languages/tgmpa-ja.po
> +"Project-Id-Version: TGM Plugin Activation\n"
Please add the version number in.

2017-08-10 02:36 UTC, mayukojpn commented on languages/tgmpa-ja.po
> +"Last-Translator: Juliette Reinders Folmer <wpplugins_nospam@adviesenzo.nl>\n"
[Done](https://github.com/TGMPA/TGM-Plugin-Activation/pull/683/commits/b4e0f9f96d143b457d5f192b3ed65766ab75fa4d)!

2017-08-10 05:21 UTC, GaryJones approved these changes
Thank you @mayukojpn !

2017-08-10 05:23 UTC, merged