Add Vietnamese Translator file
thomasgriffin/TGM-Plugin-Activation pull request #684
Opened 2017-08-11 06:17 UTC by WeAreUnique

2017-08-11 08:23 UTC, GaryJones requested changes
Thanks @WeAreUnique - just a couple of headings to tweak please.

2017-08-11 08:23 UTC, GaryJones commented on languages/tgmpa-vi_VN.po
> +"Project-Id-Version: TGM Plugin Activation by BBLand\n"
Please fix this to be "TGM Plugin Activation 2.6.1" (or whatever version this is for).

2017-08-11 08:23 UTC, GaryJones commented on languages/tgmpa-vi_VN.po
> +"Last-Translator: \n"
Please fill with your name (if you were the last translator).

2017-08-11 12:06 UTC, WeAreUnique commented on languages/tgmpa-vi_VN.po
> +"Project-Id-Version: TGM Plugin Activation by BBLand\n"
@GaryJones Updated :)

2017-08-11 12:06 UTC, WeAreUnique commented on languages/tgmpa-vi_VN.po
> +"Last-Translator: \n"
@GaryJones Updated :)

2017-08-11 12:24 UTC, GaryJones commented on languages/tgmpa-vi_VN.po
> +"Project-Id-Version: TGM Plugin Activation v2.6.1 by BBLand.net\n"
Please remove the "by BBLand.net" bit. You didn't create TGMPA; your credits for translating are in the other headers.

2017-08-11 12:26 UTC, GaryJones commented on languages/tgmpa-vi_VN.po
> +"Last-Translator: BBLand.NET\n"
The expectation here is the name and email address of the individual, not the team. See https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

2017-08-13 04:06 UTC, WeAreUnique commented on languages/tgmpa-vi_VN.po
> +"Project-Id-Version: TGM Plugin Activation v2.6.1 by BBLand.net\n"
Updated 👍

2017-08-13 05:47 UTC, GaryJones approved these changes

2017-08-13 05:47 UTC, merged